/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderModifyResponseLinesInnerAdditionalAttributesInner
 */
public class OrderModifyResponseLinesInnerAdditionalAttributesInnerTest {
    private final OrderModifyResponseLinesInnerAdditionalAttributesInner model = new OrderModifyResponseLinesInnerAdditionalAttributesInner();

    /**
     * Model tests for OrderModifyResponseLinesInnerAdditionalAttributesInner
     */
    @Test
    public void testOrderModifyResponseLinesInnerAdditionalAttributesInner() {
        // TODO: test OrderModifyResponseLinesInnerAdditionalAttributesInner
    }

    /**
     * Test the property 'attributeName'
     */
    @Test
    public void attributeNameTest() {
        // TODO: test attributeName
    }

    /**
     * Test the property 'attributeValue'
     */
    @Test
    public void attributeValueTest() {
        // TODO: test attributeValue
    }

}
