/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import xiresellers.client.model.OrderStatusAsyncNotificationRequestResourceInnerLinesInner;
import xiresellers.client.model.OrderStatusAsyncNotificationRequestResourceInnerLinksInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderStatusAsyncNotificationRequestResourceInner
 */
public class OrderStatusAsyncNotificationRequestResourceInnerTest {
    private final OrderStatusAsyncNotificationRequestResourceInner model = new OrderStatusAsyncNotificationRequestResourceInner();

    /**
     * Model tests for OrderStatusAsyncNotificationRequestResourceInner
     */
    @Test
    public void testOrderStatusAsyncNotificationRequestResourceInner() {
        // TODO: test OrderStatusAsyncNotificationRequestResourceInner
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'customerOrderNumber'
     */
    @Test
    public void customerOrderNumberTest() {
        // TODO: test customerOrderNumber
    }

    /**
     * Test the property 'orderEntryTimeStamp'
     */
    @Test
    public void orderEntryTimeStampTest() {
        // TODO: test orderEntryTimeStamp
    }

    /**
     * Test the property 'lines'
     */
    @Test
    public void linesTest() {
        // TODO: test lines
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
