/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import xiresellers.client.model.OrderDetailB2BLinesInnerServiceContractInfoContractInfo;
import xiresellers.client.model.OrderDetailB2BLinesInnerServiceContractInfoLicenseInfo;
import xiresellers.client.model.OrderDetailB2BLinesInnerServiceContractInfoSubscriptions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderDetailB2BLinesInnerServiceContractInfo
 */
public class OrderDetailB2BLinesInnerServiceContractInfoTest {
    private final OrderDetailB2BLinesInnerServiceContractInfo model = new OrderDetailB2BLinesInnerServiceContractInfo();

    /**
     * Model tests for OrderDetailB2BLinesInnerServiceContractInfo
     */
    @Test
    public void testOrderDetailB2BLinesInnerServiceContractInfo() {
        // TODO: test OrderDetailB2BLinesInnerServiceContractInfo
    }

    /**
     * Test the property 'contractInfo'
     */
    @Test
    public void contractInfoTest() {
        // TODO: test contractInfo
    }

    /**
     * Test the property 'subscriptions'
     */
    @Test
    public void subscriptionsTest() {
        // TODO: test subscriptions
    }

    /**
     * Test the property 'licenseInfo'
     */
    @Test
    public void licenseInfoTest() {
        // TODO: test licenseInfo
    }

}
