/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner
 */
public class OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInnerTest {
    private final OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner model = new OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner();

    /**
     * Model tests for OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner
     */
    @Test
    public void testOrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner() {
        // TODO: test OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner
    }

    /**
     * Test the property 'dateOfPurchase'
     */
    @Test
    public void dateOfPurchaseTest() {
        // TODO: test dateOfPurchase
    }

    /**
     * Test the property 'shipDate'
     */
    @Test
    public void shipDateTest() {
        // TODO: test shipDate
    }

    /**
     * Test the property 'primarySerialNumber'
     */
    @Test
    public void primarySerialNumberTest() {
        // TODO: test primarySerialNumber
    }

    /**
     * Test the property 'secondarySerialNumber'
     */
    @Test
    public void secondarySerialNumberTest() {
        // TODO: test secondarySerialNumber
    }

}
