/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderDetailB2BLinesInnerServiceContractInfoContractInfo
 */
public class OrderDetailB2BLinesInnerServiceContractInfoContractInfoTest {
    private final OrderDetailB2BLinesInnerServiceContractInfoContractInfo model = new OrderDetailB2BLinesInnerServiceContractInfoContractInfo();

    /**
     * Model tests for OrderDetailB2BLinesInnerServiceContractInfoContractInfo
     */
    @Test
    public void testOrderDetailB2BLinesInnerServiceContractInfoContractInfo() {
        // TODO: test OrderDetailB2BLinesInnerServiceContractInfoContractInfo
    }

    /**
     * Test the property 'contractDescription'
     */
    @Test
    public void contractDescriptionTest() {
        // TODO: test contractDescription
    }

    /**
     * Test the property 'contractNumber'
     */
    @Test
    public void contractNumberTest() {
        // TODO: test contractNumber
    }

    /**
     * Test the property 'contractStatus'
     */
    @Test
    public void contractStatusTest() {
        // TODO: test contractStatus
    }

    /**
     * Test the property 'contractStartDate'
     */
    @Test
    public void contractStartDateTest() {
        // TODO: test contractStartDate
    }

    /**
     * Test the property 'contractEndDate'
     */
    @Test
    public void contractEndDateTest() {
        // TODO: test contractEndDate
    }

    /**
     * Test the property 'contractDuration'
     */
    @Test
    public void contractDurationTest() {
        // TODO: test contractDuration
    }

}
