/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderDetailB2BLinesInnerScheduleLinesInner
 */
public class OrderDetailB2BLinesInnerScheduleLinesInnerTest {
    private final OrderDetailB2BLinesInnerScheduleLinesInner model = new OrderDetailB2BLinesInnerScheduleLinesInner();

    /**
     * Model tests for OrderDetailB2BLinesInnerScheduleLinesInner
     */
    @Test
    public void testOrderDetailB2BLinesInnerScheduleLinesInner() {
        // TODO: test OrderDetailB2BLinesInnerScheduleLinesInner
    }

    /**
     * Test the property 'lineNumber'
     */
    @Test
    public void lineNumberTest() {
        // TODO: test lineNumber
    }

    /**
     * Test the property 'scheduleLineDate'
     */
    @Test
    public void scheduleLineDateTest() {
        // TODO: test scheduleLineDate
    }

    /**
     * Test the property 'requestedQuantity'
     */
    @Test
    public void requestedQuantityTest() {
        // TODO: test requestedQuantity
    }

    /**
     * Test the property 'confirmedQuantity'
     */
    @Test
    public void confirmedQuantityTest() {
        // TODO: test confirmedQuantity
    }

    /**
     * Test the property 'goodsIssueDate'
     */
    @Test
    public void goodsIssueDateTest() {
        // TODO: test goodsIssueDate
    }

}
