/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostCreateorderV7500Response
 */
public class PostCreateorderV7500ResponseTest {
    private final PostCreateorderV7500Response model = new PostCreateorderV7500Response();

    /**
     * Model tests for PostCreateorderV7500Response
     */
    @Test
    public void testPostCreateorderV7500Response() {
        // TODO: test PostCreateorderV7500Response
    }

    /**
     * Test the property 'traceid'
     */
    @Test
    public void traceidTest() {
        // TODO: test traceid
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

}
