/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductDetailResponseSubscriptionDetailsInnerOptionsInner
 */
public class ProductDetailResponseSubscriptionDetailsInnerOptionsInnerTest {
    private final ProductDetailResponseSubscriptionDetailsInnerOptionsInner model = new ProductDetailResponseSubscriptionDetailsInnerOptionsInner();

    /**
     * Model tests for ProductDetailResponseSubscriptionDetailsInnerOptionsInner
     */
    @Test
    public void testProductDetailResponseSubscriptionDetailsInnerOptionsInner() {
        // TODO: test ProductDetailResponseSubscriptionDetailsInnerOptionsInner
    }

    /**
     * Test the property 'resourceId'
     */
    @Test
    public void resourceIdTest() {
        // TODO: test resourceId
    }

    /**
     * Test the property 'resourceName'
     */
    @Test
    public void resourceNameTest() {
        // TODO: test resourceName
    }

    /**
     * Test the property 'vendorPartNumber'
     */
    @Test
    public void vendorPartNumberTest() {
        // TODO: test vendorPartNumber
    }

    /**
     * Test the property 'minUnits'
     */
    @Test
    public void minUnitsTest() {
        // TODO: test minUnits
    }

    /**
     * Test the property 'maxUnits'
     */
    @Test
    public void maxUnitsTest() {
        // TODO: test maxUnits
    }

    /**
     * Test the property 'dependsOn'
     */
    @Test
    public void dependsOnTest() {
        // TODO: test dependsOn
    }

}
