/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QuoteCreateWebhookResponseResourceProductsInnerPrice
 */
public class QuoteCreateWebhookResponseResourceProductsInnerPriceTest {
    private final QuoteCreateWebhookResponseResourceProductsInnerPrice model = new QuoteCreateWebhookResponseResourceProductsInnerPrice();

    /**
     * Model tests for QuoteCreateWebhookResponseResourceProductsInnerPrice
     */
    @Test
    public void testQuoteCreateWebhookResponseResourceProductsInnerPrice() {
        // TODO: test QuoteCreateWebhookResponseResourceProductsInnerPrice
    }

    /**
     * Test the property 'quotePrice'
     */
    @Test
    public void quotePriceTest() {
        // TODO: test quotePrice
    }

    /**
     * Test the property 'msrp'
     */
    @Test
    public void msrpTest() {
        // TODO: test msrp
    }

    /**
     * Test the property 'extendedMsrp'
     */
    @Test
    public void extendedMsrpTest() {
        // TODO: test extendedMsrp
    }

    /**
     * Test the property 'extendedQuotePrice'
     */
    @Test
    public void extendedQuotePriceTest() {
        // TODO: test extendedQuotePrice
    }

    /**
     * Test the property 'discountOffList'
     */
    @Test
    public void discountOffListTest() {
        // TODO: test discountOffList
    }

}
