/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QuoteDetailsResponseResellerInfo
 */
public class QuoteDetailsResponseResellerInfoTest {
    private final QuoteDetailsResponseResellerInfo model = new QuoteDetailsResponseResellerInfo();

    /**
     * Model tests for QuoteDetailsResponseResellerInfo
     */
    @Test
    public void testQuoteDetailsResponseResellerInfo() {
        // TODO: test QuoteDetailsResponseResellerInfo
    }

    /**
     * Test the property 'contact'
     */
    @Test
    public void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'customerNumber'
     */
    @Test
    public void customerNumberTest() {
        // TODO: test customerNumber
    }

}
