/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import xiresellers.client.model.ProductSearchResponseCatalogInner;
import xiresellers.client.model.ProductSearchResponseSubscriptionCatalogInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import xiresellers.client.JSON;

/**
 * ProductSearchResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-05T07:27:07.209261089Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class ProductSearchResponse {
  public static final String SERIALIZED_NAME_RECORDS_FOUND = "recordsFound";
  @SerializedName(SERIALIZED_NAME_RECORDS_FOUND)
  @javax.annotation.Nullable
  private Integer recordsFound;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "pageSize";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  @javax.annotation.Nullable
  private Integer pageSize;

  public static final String SERIALIZED_NAME_PAGE_NUMBER = "pageNumber";
  @SerializedName(SERIALIZED_NAME_PAGE_NUMBER)
  @javax.annotation.Nullable
  private Integer pageNumber;

  public static final String SERIALIZED_NAME_CATALOG = "catalog";
  @SerializedName(SERIALIZED_NAME_CATALOG)
  @javax.annotation.Nullable
  private List<ProductSearchResponseCatalogInner> catalog = new ArrayList<>();

  public static final String SERIALIZED_NAME_SUBSCRIPTION_CATALOG = "subscriptionCatalog";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_CATALOG)
  @javax.annotation.Nullable
  private List<ProductSearchResponseSubscriptionCatalogInner> subscriptionCatalog = new ArrayList<>();

  public static final String SERIALIZED_NAME_NEXT_PAGE = "nextPage";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE)
  @javax.annotation.Nullable
  private String nextPage;

  public static final String SERIALIZED_NAME_PREVIOUS_PAGE = "previousPage";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_PAGE)
  @javax.annotation.Nullable
  private String previousPage;

  public ProductSearchResponse() {
  }

  public ProductSearchResponse recordsFound(@javax.annotation.Nullable Integer recordsFound) {
    this.recordsFound = recordsFound;
    return this;
  }

  /**
   * The number of recourds found for the search.
   * @return recordsFound
   */
  @javax.annotation.Nullable
  public Integer getRecordsFound() {
    return recordsFound;
  }

  public void setRecordsFound(@javax.annotation.Nullable Integer recordsFound) {
    this.recordsFound = recordsFound;
  }


  public ProductSearchResponse pageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * The number of results per page. Default is 25.
   * @return pageSize
   */
  @javax.annotation.Nullable
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
  }


  public ProductSearchResponse pageNumber(@javax.annotation.Nullable Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

  /**
   * current page number default is 1
   * @return pageNumber
   */
  @javax.annotation.Nullable
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(@javax.annotation.Nullable Integer pageNumber) {
    this.pageNumber = pageNumber;
  }


  public ProductSearchResponse catalog(@javax.annotation.Nullable List<ProductSearchResponseCatalogInner> catalog) {
    this.catalog = catalog;
    return this;
  }

  public ProductSearchResponse addCatalogItem(ProductSearchResponseCatalogInner catalogItem) {
    if (this.catalog == null) {
      this.catalog = new ArrayList<>();
    }
    this.catalog.add(catalogItem);
    return this;
  }

  /**
   * Get catalog
   * @return catalog
   */
  @javax.annotation.Nullable
  public List<ProductSearchResponseCatalogInner> getCatalog() {
    return catalog;
  }

  public void setCatalog(@javax.annotation.Nullable List<ProductSearchResponseCatalogInner> catalog) {
    this.catalog = catalog;
  }


  public ProductSearchResponse subscriptionCatalog(@javax.annotation.Nullable List<ProductSearchResponseSubscriptionCatalogInner> subscriptionCatalog) {
    this.subscriptionCatalog = subscriptionCatalog;
    return this;
  }

  public ProductSearchResponse addSubscriptionCatalogItem(ProductSearchResponseSubscriptionCatalogInner subscriptionCatalogItem) {
    if (this.subscriptionCatalog == null) {
      this.subscriptionCatalog = new ArrayList<>();
    }
    this.subscriptionCatalog.add(subscriptionCatalogItem);
    return this;
  }

  /**
   * Get subscriptionCatalog
   * @return subscriptionCatalog
   */
  @javax.annotation.Nullable
  public List<ProductSearchResponseSubscriptionCatalogInner> getSubscriptionCatalog() {
    return subscriptionCatalog;
  }

  public void setSubscriptionCatalog(@javax.annotation.Nullable List<ProductSearchResponseSubscriptionCatalogInner> subscriptionCatalog) {
    this.subscriptionCatalog = subscriptionCatalog;
  }


  public ProductSearchResponse nextPage(@javax.annotation.Nullable String nextPage) {
    this.nextPage = nextPage;
    return this;
  }

  /**
   * link/URL for accessing next page.
   * @return nextPage
   */
  @javax.annotation.Nullable
  public String getNextPage() {
    return nextPage;
  }

  public void setNextPage(@javax.annotation.Nullable String nextPage) {
    this.nextPage = nextPage;
  }


  public ProductSearchResponse previousPage(@javax.annotation.Nullable String previousPage) {
    this.previousPage = previousPage;
    return this;
  }

  /**
   * link/URL for accessing previous page.
   * @return previousPage
   */
  @javax.annotation.Nullable
  public String getPreviousPage() {
    return previousPage;
  }

  public void setPreviousPage(@javax.annotation.Nullable String previousPage) {
    this.previousPage = previousPage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductSearchResponse productSearchResponse = (ProductSearchResponse) o;
    return Objects.equals(this.recordsFound, productSearchResponse.recordsFound) &&
        Objects.equals(this.pageSize, productSearchResponse.pageSize) &&
        Objects.equals(this.pageNumber, productSearchResponse.pageNumber) &&
        Objects.equals(this.catalog, productSearchResponse.catalog) &&
        Objects.equals(this.subscriptionCatalog, productSearchResponse.subscriptionCatalog) &&
        Objects.equals(this.nextPage, productSearchResponse.nextPage) &&
        Objects.equals(this.previousPage, productSearchResponse.previousPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recordsFound, pageSize, pageNumber, catalog, subscriptionCatalog, nextPage, previousPage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductSearchResponse {\n");
    sb.append("    recordsFound: ").append(toIndentedString(recordsFound)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    catalog: ").append(toIndentedString(catalog)).append("\n");
    sb.append("    subscriptionCatalog: ").append(toIndentedString(subscriptionCatalog)).append("\n");
    sb.append("    nextPage: ").append(toIndentedString(nextPage)).append("\n");
    sb.append("    previousPage: ").append(toIndentedString(previousPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("recordsFound");
    openapiFields.add("pageSize");
    openapiFields.add("pageNumber");
    openapiFields.add("catalog");
    openapiFields.add("subscriptionCatalog");
    openapiFields.add("nextPage");
    openapiFields.add("previousPage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProductSearchResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProductSearchResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProductSearchResponse is not found in the empty JSON string", ProductSearchResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProductSearchResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProductSearchResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("catalog") != null && !jsonObj.get("catalog").isJsonNull()) {
        JsonArray jsonArraycatalog = jsonObj.getAsJsonArray("catalog");
        if (jsonArraycatalog != null) {
          // ensure the json data is an array
          if (!jsonObj.get("catalog").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `catalog` to be an array in the JSON string but got `%s`", jsonObj.get("catalog").toString()));
          }

          // validate the optional field `catalog` (array)
          for (int i = 0; i < jsonArraycatalog.size(); i++) {
            ProductSearchResponseCatalogInner.validateJsonElement(jsonArraycatalog.get(i));
          };
        }
      }
      if (jsonObj.get("subscriptionCatalog") != null && !jsonObj.get("subscriptionCatalog").isJsonNull()) {
        JsonArray jsonArraysubscriptionCatalog = jsonObj.getAsJsonArray("subscriptionCatalog");
        if (jsonArraysubscriptionCatalog != null) {
          // ensure the json data is an array
          if (!jsonObj.get("subscriptionCatalog").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `subscriptionCatalog` to be an array in the JSON string but got `%s`", jsonObj.get("subscriptionCatalog").toString()));
          }

          // validate the optional field `subscriptionCatalog` (array)
          for (int i = 0; i < jsonArraysubscriptionCatalog.size(); i++) {
            ProductSearchResponseSubscriptionCatalogInner.validateJsonElement(jsonArraysubscriptionCatalog.get(i));
          };
        }
      }
      if ((jsonObj.get("nextPage") != null && !jsonObj.get("nextPage").isJsonNull()) && !jsonObj.get("nextPage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextPage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextPage").toString()));
      }
      if ((jsonObj.get("previousPage") != null && !jsonObj.get("previousPage").isJsonNull()) && !jsonObj.get("previousPage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `previousPage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("previousPage").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProductSearchResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProductSearchResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProductSearchResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProductSearchResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ProductSearchResponse>() {
           @Override
           public void write(JsonWriter out, ProductSearchResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProductSearchResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProductSearchResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProductSearchResponse
   * @throws IOException if the JSON string is invalid with respect to ProductSearchResponse
   */
  public static ProductSearchResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProductSearchResponse.class);
  }

  /**
   * Convert an instance of ProductSearchResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

