/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import xiresellers.client.model.QuoteCreateRequestEndUserInfo;
import xiresellers.client.model.QuoteCreateRequestProductsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import xiresellers.client.JSON;

/**
 * QuoteCreateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-09T06:25:58.100608330Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class QuoteCreateRequest {
  public static final String SERIALIZED_NAME_QUOTE_NAME = "quoteName";
  @SerializedName(SERIALIZED_NAME_QUOTE_NAME)
  @javax.annotation.Nullable
  private String quoteName;

  public static final String SERIALIZED_NAME_FIRSTNAME = "firstname";
  @SerializedName(SERIALIZED_NAME_FIRSTNAME)
  @javax.annotation.Nullable
  private String firstname;

  public static final String SERIALIZED_NAME_LASTNAME = "lastname";
  @SerializedName(SERIALIZED_NAME_LASTNAME)
  @javax.annotation.Nullable
  private String lastname;

  public static final String SERIALIZED_NAME_CUSTOMER_CONTACT = "customerContact";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_CONTACT)
  @javax.annotation.Nullable
  private String customerContact;

  public static final String SERIALIZED_NAME_QUOTE_EXPIRY_DATE = "quoteExpiryDate";
  @SerializedName(SERIALIZED_NAME_QUOTE_EXPIRY_DATE)
  @javax.annotation.Nullable
  private String quoteExpiryDate;

  public static final String SERIALIZED_NAME_CUSTOMER_NEED = "customerNeed";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_NEED)
  @javax.annotation.Nullable
  private String customerNeed;

  public static final String SERIALIZED_NAME_END_USER_INFO = "endUserInfo";
  @SerializedName(SERIALIZED_NAME_END_USER_INFO)
  @javax.annotation.Nullable
  private QuoteCreateRequestEndUserInfo endUserInfo;

  public static final String SERIALIZED_NAME_DEAL_ID = "dealId";
  @SerializedName(SERIALIZED_NAME_DEAL_ID)
  @javax.annotation.Nullable
  private String dealId;

  public static final String SERIALIZED_NAME_PRICING_TYPE = "pricingType";
  @SerializedName(SERIALIZED_NAME_PRICING_TYPE)
  @javax.annotation.Nullable
  private String pricingType;

  public static final String SERIALIZED_NAME_SEND_QUOTE_COPY = "sendQuoteCopy";
  @SerializedName(SERIALIZED_NAME_SEND_QUOTE_COPY)
  @javax.annotation.Nullable
  private String sendQuoteCopy;

  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @SerializedName(SERIALIZED_NAME_PRODUCTS)
  @javax.annotation.Nullable
  private List<QuoteCreateRequestProductsInner> products = new ArrayList<>();

  public QuoteCreateRequest() {
  }

  public QuoteCreateRequest quoteName(@javax.annotation.Nullable String quoteName) {
    this.quoteName = quoteName;
    return this;
  }

  /**
   * Quote Name given to quote by sales team or system generated. Generally used as a reference to identify the quote.
   * @return quoteName
   */
  @javax.annotation.Nullable
  public String getQuoteName() {
    return quoteName;
  }

  public void setQuoteName(@javax.annotation.Nullable String quoteName) {
    this.quoteName = quoteName;
  }


  public QuoteCreateRequest firstname(@javax.annotation.Nullable String firstname) {
    this.firstname = firstname;
    return this;
  }

  /**
   * Logged in Users firstname
   * @return firstname
   */
  @javax.annotation.Nullable
  public String getFirstname() {
    return firstname;
  }

  public void setFirstname(@javax.annotation.Nullable String firstname) {
    this.firstname = firstname;
  }


  public QuoteCreateRequest lastname(@javax.annotation.Nullable String lastname) {
    this.lastname = lastname;
    return this;
  }

  /**
   * Logged in Users Lastname
   * @return lastname
   */
  @javax.annotation.Nullable
  public String getLastname() {
    return lastname;
  }

  public void setLastname(@javax.annotation.Nullable String lastname) {
    this.lastname = lastname;
  }


  public QuoteCreateRequest customerContact(@javax.annotation.Nullable String customerContact) {
    this.customerContact = customerContact;
    return this;
  }

  /**
   * Logged in Users email address contact.
   * @return customerContact
   */
  @javax.annotation.Nullable
  public String getCustomerContact() {
    return customerContact;
  }

  public void setCustomerContact(@javax.annotation.Nullable String customerContact) {
    this.customerContact = customerContact;
  }


  public QuoteCreateRequest quoteExpiryDate(@javax.annotation.Nullable String quoteExpiryDate) {
    this.quoteExpiryDate = quoteExpiryDate;
    return this;
  }

  /**
   * The date on which a quote will expire.
   * @return quoteExpiryDate
   */
  @javax.annotation.Nullable
  public String getQuoteExpiryDate() {
    return quoteExpiryDate;
  }

  public void setQuoteExpiryDate(@javax.annotation.Nullable String quoteExpiryDate) {
    this.quoteExpiryDate = quoteExpiryDate;
  }


  public QuoteCreateRequest customerNeed(@javax.annotation.Nullable String customerNeed) {
    this.customerNeed = customerNeed;
    return this;
  }

  /**
   * Any special need from the customer.
   * @return customerNeed
   */
  @javax.annotation.Nullable
  public String getCustomerNeed() {
    return customerNeed;
  }

  public void setCustomerNeed(@javax.annotation.Nullable String customerNeed) {
    this.customerNeed = customerNeed;
  }


  public QuoteCreateRequest endUserInfo(@javax.annotation.Nullable QuoteCreateRequestEndUserInfo endUserInfo) {
    this.endUserInfo = endUserInfo;
    return this;
  }

  /**
   * Get endUserInfo
   * @return endUserInfo
   */
  @javax.annotation.Nullable
  public QuoteCreateRequestEndUserInfo getEndUserInfo() {
    return endUserInfo;
  }

  public void setEndUserInfo(@javax.annotation.Nullable QuoteCreateRequestEndUserInfo endUserInfo) {
    this.endUserInfo = endUserInfo;
  }


  public QuoteCreateRequest dealId(@javax.annotation.Nullable String dealId) {
    this.dealId = dealId;
    return this;
  }

  /**
   * Price discount identifyer to specify a pricing discount that has been applied to the quote.
   * @return dealId
   */
  @javax.annotation.Nullable
  public String getDealId() {
    return dealId;
  }

  public void setDealId(@javax.annotation.Nullable String dealId) {
    this.dealId = dealId;
  }


  public QuoteCreateRequest pricingType(@javax.annotation.Nullable String pricingType) {
    this.pricingType = pricingType;
    return this;
  }

  /**
   * Pricing type of the quote.
   * @return pricingType
   */
  @javax.annotation.Nullable
  public String getPricingType() {
    return pricingType;
  }

  public void setPricingType(@javax.annotation.Nullable String pricingType) {
    this.pricingType = pricingType;
  }


  public QuoteCreateRequest sendQuoteCopy(@javax.annotation.Nullable String sendQuoteCopy) {
    this.sendQuoteCopy = sendQuoteCopy;
    return this;
  }

  /**
   * List of email addressed to whom the quote will be emailed after it&#39;s created. (Max 10 email ids)
   * @return sendQuoteCopy
   */
  @javax.annotation.Nullable
  public String getSendQuoteCopy() {
    return sendQuoteCopy;
  }

  public void setSendQuoteCopy(@javax.annotation.Nullable String sendQuoteCopy) {
    this.sendQuoteCopy = sendQuoteCopy;
  }


  public QuoteCreateRequest products(@javax.annotation.Nullable List<QuoteCreateRequestProductsInner> products) {
    this.products = products;
    return this;
  }

  public QuoteCreateRequest addProductsItem(QuoteCreateRequestProductsInner productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

  /**
   * Get products
   * @return products
   */
  @javax.annotation.Nullable
  public List<QuoteCreateRequestProductsInner> getProducts() {
    return products;
  }

  public void setProducts(@javax.annotation.Nullable List<QuoteCreateRequestProductsInner> products) {
    this.products = products;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteCreateRequest quoteCreateRequest = (QuoteCreateRequest) o;
    return Objects.equals(this.quoteName, quoteCreateRequest.quoteName) &&
        Objects.equals(this.firstname, quoteCreateRequest.firstname) &&
        Objects.equals(this.lastname, quoteCreateRequest.lastname) &&
        Objects.equals(this.customerContact, quoteCreateRequest.customerContact) &&
        Objects.equals(this.quoteExpiryDate, quoteCreateRequest.quoteExpiryDate) &&
        Objects.equals(this.customerNeed, quoteCreateRequest.customerNeed) &&
        Objects.equals(this.endUserInfo, quoteCreateRequest.endUserInfo) &&
        Objects.equals(this.dealId, quoteCreateRequest.dealId) &&
        Objects.equals(this.pricingType, quoteCreateRequest.pricingType) &&
        Objects.equals(this.sendQuoteCopy, quoteCreateRequest.sendQuoteCopy) &&
        Objects.equals(this.products, quoteCreateRequest.products);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quoteName, firstname, lastname, customerContact, quoteExpiryDate, customerNeed, endUserInfo, dealId, pricingType, sendQuoteCopy, products);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteCreateRequest {\n");
    sb.append("    quoteName: ").append(toIndentedString(quoteName)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    customerContact: ").append(toIndentedString(customerContact)).append("\n");
    sb.append("    quoteExpiryDate: ").append(toIndentedString(quoteExpiryDate)).append("\n");
    sb.append("    customerNeed: ").append(toIndentedString(customerNeed)).append("\n");
    sb.append("    endUserInfo: ").append(toIndentedString(endUserInfo)).append("\n");
    sb.append("    dealId: ").append(toIndentedString(dealId)).append("\n");
    sb.append("    pricingType: ").append(toIndentedString(pricingType)).append("\n");
    sb.append("    sendQuoteCopy: ").append(toIndentedString(sendQuoteCopy)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("quoteName");
    openapiFields.add("firstname");
    openapiFields.add("lastname");
    openapiFields.add("customerContact");
    openapiFields.add("quoteExpiryDate");
    openapiFields.add("customerNeed");
    openapiFields.add("endUserInfo");
    openapiFields.add("dealId");
    openapiFields.add("pricingType");
    openapiFields.add("sendQuoteCopy");
    openapiFields.add("products");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QuoteCreateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QuoteCreateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QuoteCreateRequest is not found in the empty JSON string", QuoteCreateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QuoteCreateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `QuoteCreateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("quoteName") != null && !jsonObj.get("quoteName").isJsonNull()) && !jsonObj.get("quoteName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `quoteName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quoteName").toString()));
      }
      if ((jsonObj.get("firstname") != null && !jsonObj.get("firstname").isJsonNull()) && !jsonObj.get("firstname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstname").toString()));
      }
      if ((jsonObj.get("lastname") != null && !jsonObj.get("lastname").isJsonNull()) && !jsonObj.get("lastname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastname").toString()));
      }
      if ((jsonObj.get("customerContact") != null && !jsonObj.get("customerContact").isJsonNull()) && !jsonObj.get("customerContact").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerContact` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerContact").toString()));
      }
      if ((jsonObj.get("quoteExpiryDate") != null && !jsonObj.get("quoteExpiryDate").isJsonNull()) && !jsonObj.get("quoteExpiryDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `quoteExpiryDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quoteExpiryDate").toString()));
      }
      if ((jsonObj.get("customerNeed") != null && !jsonObj.get("customerNeed").isJsonNull()) && !jsonObj.get("customerNeed").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerNeed` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerNeed").toString()));
      }
      // validate the optional field `endUserInfo`
      if (jsonObj.get("endUserInfo") != null && !jsonObj.get("endUserInfo").isJsonNull()) {
        QuoteCreateRequestEndUserInfo.validateJsonElement(jsonObj.get("endUserInfo"));
      }
      if ((jsonObj.get("dealId") != null && !jsonObj.get("dealId").isJsonNull()) && !jsonObj.get("dealId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dealId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dealId").toString()));
      }
      if ((jsonObj.get("pricingType") != null && !jsonObj.get("pricingType").isJsonNull()) && !jsonObj.get("pricingType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pricingType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pricingType").toString()));
      }
      if ((jsonObj.get("sendQuoteCopy") != null && !jsonObj.get("sendQuoteCopy").isJsonNull()) && !jsonObj.get("sendQuoteCopy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendQuoteCopy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendQuoteCopy").toString()));
      }
      if (jsonObj.get("products") != null && !jsonObj.get("products").isJsonNull()) {
        JsonArray jsonArrayproducts = jsonObj.getAsJsonArray("products");
        if (jsonArrayproducts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("products").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `products` to be an array in the JSON string but got `%s`", jsonObj.get("products").toString()));
          }

          // validate the optional field `products` (array)
          for (int i = 0; i < jsonArrayproducts.size(); i++) {
            QuoteCreateRequestProductsInner.validateJsonElement(jsonArrayproducts.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QuoteCreateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QuoteCreateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QuoteCreateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QuoteCreateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<QuoteCreateRequest>() {
           @Override
           public void write(JsonWriter out, QuoteCreateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QuoteCreateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QuoteCreateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QuoteCreateRequest
   * @throws IOException if the JSON string is invalid with respect to QuoteCreateRequest
   */
  public static QuoteCreateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QuoteCreateRequest.class);
  }

  /**
   * Convert an instance of QuoteCreateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

