/*
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import xiresellers.client.model.VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import xiresellers.client.JSON;

/**
 * VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-19T09:55:15.223059622Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner {
  public static final String SERIALIZED_NAME_ATTRIBUTE_NAME = "attributeName";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_NAME)
  @javax.annotation.Nullable
  private String attributeName;

  public static final String SERIALIZED_NAME_ATTRIBUTE_VALUE = "attributeValue";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_VALUE)
  @javax.annotation.Nullable
  private String attributeValue;

  public static final String SERIALIZED_NAME_ATTRIBUTE_DESCRIPTION = "attributeDescription";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_DESCRIPTION)
  @javax.annotation.Nullable
  private String attributeDescription;

  public static final String SERIALIZED_NAME_ATTRIBUTE_HINT = "attributeHint";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_HINT)
  @javax.annotation.Nullable
  private String attributeHint;

  public static final String SERIALIZED_NAME_CHOICES = "choices";
  @SerializedName(SERIALIZED_NAME_CHOICES)
  @javax.annotation.Nullable
  private List<VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner> choices = new ArrayList<>();

  public VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner() {
  }

  public VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner attributeName(@javax.annotation.Nullable String attributeName) {
    this.attributeName = attributeName;
    return this;
  }

  /**
   * The name of the vendor mandatory field.
   * @return attributeName
   */
  @javax.annotation.Nullable
  public String getAttributeName() {
    return attributeName;
  }

  public void setAttributeName(@javax.annotation.Nullable String attributeName) {
    this.attributeName = attributeName;
  }


  public VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner attributeValue(@javax.annotation.Nullable String attributeValue) {
    this.attributeValue = attributeValue;
    return this;
  }

  /**
   * The value of the vendor mandatory field.
   * @return attributeValue
   */
  @javax.annotation.Nullable
  public String getAttributeValue() {
    return attributeValue;
  }

  public void setAttributeValue(@javax.annotation.Nullable String attributeValue) {
    this.attributeValue = attributeValue;
  }


  public VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner attributeDescription(@javax.annotation.Nullable String attributeDescription) {
    this.attributeDescription = attributeDescription;
    return this;
  }

  /**
   * The description of the vendor mandatory field.
   * @return attributeDescription
   */
  @javax.annotation.Nullable
  public String getAttributeDescription() {
    return attributeDescription;
  }

  public void setAttributeDescription(@javax.annotation.Nullable String attributeDescription) {
    this.attributeDescription = attributeDescription;
  }


  public VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner attributeHint(@javax.annotation.Nullable String attributeHint) {
    this.attributeHint = attributeHint;
    return this;
  }

  /**
   * The hint of the vendor mandatory field.
   * @return attributeHint
   */
  @javax.annotation.Nullable
  public String getAttributeHint() {
    return attributeHint;
  }

  public void setAttributeHint(@javax.annotation.Nullable String attributeHint) {
    this.attributeHint = attributeHint;
  }


  public VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner choices(@javax.annotation.Nullable List<VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner> choices) {
    this.choices = choices;
    return this;
  }

  public VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner addChoicesItem(VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner choicesItem) {
    if (this.choices == null) {
      this.choices = new ArrayList<>();
    }
    this.choices.add(choicesItem);
    return this;
  }

  /**
   * Get choices
   * @return choices
   */
  @javax.annotation.Nullable
  public List<VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner> getChoices() {
    return choices;
  }

  public void setChoices(@javax.annotation.Nullable List<VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner> choices) {
    this.choices = choices;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner vendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner = (VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner) o;
    return Objects.equals(this.attributeName, vendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.attributeName) &&
        Objects.equals(this.attributeValue, vendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.attributeValue) &&
        Objects.equals(this.attributeDescription, vendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.attributeDescription) &&
        Objects.equals(this.attributeHint, vendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.attributeHint) &&
        Objects.equals(this.choices, vendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.choices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeName, attributeValue, attributeDescription, attributeHint, choices);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner {\n");
    sb.append("    attributeName: ").append(toIndentedString(attributeName)).append("\n");
    sb.append("    attributeValue: ").append(toIndentedString(attributeValue)).append("\n");
    sb.append("    attributeDescription: ").append(toIndentedString(attributeDescription)).append("\n");
    sb.append("    attributeHint: ").append(toIndentedString(attributeHint)).append("\n");
    sb.append("    choices: ").append(toIndentedString(choices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("attributeName", "attributeValue", "attributeDescription", "attributeHint", "choices"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner is not found in the empty JSON string", VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("attributeName") != null && !jsonObj.get("attributeName").isJsonNull()) && !jsonObj.get("attributeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `attributeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attributeName").toString()));
      }
      if ((jsonObj.get("attributeValue") != null && !jsonObj.get("attributeValue").isJsonNull()) && !jsonObj.get("attributeValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `attributeValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attributeValue").toString()));
      }
      if ((jsonObj.get("attributeDescription") != null && !jsonObj.get("attributeDescription").isJsonNull()) && !jsonObj.get("attributeDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `attributeDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attributeDescription").toString()));
      }
      if ((jsonObj.get("attributeHint") != null && !jsonObj.get("attributeHint").isJsonNull()) && !jsonObj.get("attributeHint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `attributeHint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attributeHint").toString()));
      }
      if (jsonObj.get("choices") != null && !jsonObj.get("choices").isJsonNull()) {
        JsonArray jsonArraychoices = jsonObj.getAsJsonArray("choices");
        if (jsonArraychoices != null) {
          // ensure the json data is an array
          if (!jsonObj.get("choices").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `choices` to be an array in the JSON string but got `%s`", jsonObj.get("choices").toString()));
          }

          // validate the optional field `choices` (array)
          for (int i = 0; i < jsonArraychoices.size(); i++) {
            VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner.validateJsonElement(jsonArraychoices.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner>() {
           @Override
           public void write(JsonWriter out, VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner
   * @throws IOException if the JSON string is invalid with respect to VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner
   */
  public static VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner.class);
  }

  /**
   * Convert an instance of VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

